language: python
sudo: false
cache:
  directories:
  - eggs
  - downloads
python:
  - 3.7
install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout -N buildout:download-cache=downloads
script:
  - bin/code-analysis
  - bin/test
